# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 350)
        self.Container = QtWidgets.QWidget(MainWindow)
        self.Container.setObjectName("Container")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Container)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Space = QtWidgets.QGridLayout()
        self.Space.setObjectName("Space")
        self.gridLayout_2.addLayout(self.Space, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.Container)
        self.MenuBar = QtWidgets.QMenuBar(MainWindow)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 630, 23))
        self.MenuBar.setObjectName("MenuBar")
        self.Menu = QtWidgets.QMenu(self.MenuBar)
        self.Menu.setObjectName("Menu")
        MainWindow.setMenuBar(self.MenuBar)
        self.StatusBar = QtWidgets.QStatusBar(MainWindow)
        self.StatusBar.setObjectName("StatusBar")
        MainWindow.setStatusBar(self.StatusBar)
        self.OpenMusicManager = QtWidgets.QAction(MainWindow)
        self.OpenMusicManager.setObjectName("OpenMusicManager")
        self.Menu.addAction(self.OpenMusicManager)
        self.MenuBar.addAction(self.Menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Menu.setTitle(_translate("MainWindow", "音乐"))
        self.OpenMusicManager.setText(_translate("MainWindow", "音乐管理器"))
